
import java.util.Stack;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class F3 extends javax.swing.JFrame {

    /**
     * Creates new form F3
     */
    public F3() {
        initComponents();
        choice2.add("binary");
        choice2.add("decimal");
        choice2.add("hexadecimal");
        choice2.add("octal");
         choice1.add("binary");
        choice1.add("decimal");
        choice1.add("hexadecimal");
        choice1.add("octal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new java.awt.Label();
        b1 = new java.awt.Button();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        t2 = new javax.swing.JTextField();
        choice1 = new java.awt.Choice();
        t1 = new javax.swing.JTextField();
        choice2 = new java.awt.Choice();
        label3 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));

        l1.setAlignment(java.awt.Label.CENTER);
        l1.setBackground(new java.awt.Color(0, 153, 255));
        l1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        l1.setForeground(new java.awt.Color(240, 240, 240));
        l1.setText("Base Convertor");

        b1.setBackground(new java.awt.Color(0, 153, 204));
        b1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        b1.setLabel("Menu");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        label1.setText("Select The Type Of Unit You Want To Convert");

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("From");

        t2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        t2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        choice1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        choice1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice1ItemStateChanged(evt);
            }
        });

        t1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        choice2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        choice2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice2ItemStateChanged(evt);
            }
        });

        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setText("To");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(choice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 269, Short.MAX_VALUE)))))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choice2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choice1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice1ItemStateChanged
                 // TODO add your handling code here:
    }//GEN-LAST:event_choice1ItemStateChanged

    private void choice2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice2ItemStateChanged
              String s=choice1.getSelectedItem();
               String s1=choice2.getSelectedItem();
               String s2=t1.getText();
                Double d=Double.parseDouble(s2);
                 Stack st=new Stack();
                 int n=s2.length();
              if((s.equalsIgnoreCase("decimal"))&&(s1.equalsIgnoreCase("binary")));
              {
                 decimalToBinary(d,st,n);
                 
              }
               if((s.equalsIgnoreCase("decimal"))&&(s1.equalsIgnoreCase("octal")));
              {
                 decimalToOctal(d,st,n);
                 
              }
               if((s.equalsIgnoreCase("decimal"))&&(s1.equalsIgnoreCase("hexadecimal")));
              {
                 decimalToHexa(d,st,n);
                 
              }
               if((s.equalsIgnoreCase("binary"))&&(s1.equalsIgnoreCase("decimal")));
              {  
                int r= binaryToDecimal(d,n);
                t2.setText(r+"");
                 
              }
               if((s.equalsIgnoreCase("binary"))&&(s1.equalsIgnoreCase("octal")));
              {
                  double r=binaryToDecimal(d,n);
                 decimalToOctal(r,st,n);
                 
              }
              if((s.equalsIgnoreCase("binary"))&&(s1.equalsIgnoreCase("hexadecimal")));
              {
                  double r=binaryToDecimal(d,n);
                 decimalToHexa(r,st,n);
                 
              }
              if((s.equalsIgnoreCase("octal"))&&(s1.equalsIgnoreCase("decimal")));
              {  
                int r= octalToDecimal(d,n);
                t2.setText(r+"");
                 
              }
               if((s.equalsIgnoreCase("octal"))&&(s1.equalsIgnoreCase("binary")));
              {  
                double r= octalToDecimal(d,n);
                decimalToBinary(r,st,n);
                 
              }
               if((s.equalsIgnoreCase("octal"))&&(s1.equalsIgnoreCase("hexadecimal")));
              {  
                double r= octalToDecimal(d,n);
                decimalToHexa(r,st,n);
                 
              }
              if((s.equalsIgnoreCase("hexadecimal"))&&(s1.equalsIgnoreCase("decimal")));
              {  
                int r= hexaToDecimal(d,n);
                t2.setText(r+"");
                 
              }// TODO add your handling code here:
    }//GEN-LAST:event_choice2ItemStateChanged

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
              dispose();
              new NewJFrame().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed
public int binaryToDecimal(Double d,int n)
    {
        int sum=0;
        for(int i=0;i<n;i++)
        {
            int r=(int)(d%10);
            sum=sum+r*(2^i);
            d=d/10;
        }
        return (sum);
    }
    public int octalToDecimal(Double d,int n)
    {
        int sum=0;
        for(int i=0;i<n;i++)
        {
            int r=(int)(d%10);
            sum=sum+r*(8^i);
            d=d/10;
        }
        return (sum);
    }
     public int hexaToDecimal(Double d,int n)
     {
         return 0;
     }
public void decimalToBinary(Double d,Stack st,int n)
    {
         while(d!=0)
                  {
                      st.push(d%2);
                      d=d/2;
                  }
                  while(n!=0)
                  {
                      t2.setText((st.pop())+"");
                      n--;
                  }
    }
public void decimalToOctal(Double d,Stack st,int n)
    {
         while(d!=0)
                  {
                      st.push(d%8);
                      d=d/8;
                  }
                  while(n!=0)
                  {
                      t2.setText((st.pop())+"");
                      n--;
                  }
    }
public void decimalToHexa(Double r,Stack st,int n)
    {
         while(r!=0)
                  {
                     double e=r%16;
                     if(e==10)
                         st.push("A");
                     else if(e==11)
                         st.push("B");
                     else if(e==12)
                         st.push("C");
                     else if(e==13)
                         st.push("D");
                     else if(e==14)
                         st.push("E");
                     else if(e==15)
                         st.push("F");
                     else
                         st.push(e);
                      r=r/16;
                  }
                  while(n!=0)
                  {
                     t2.setText((st.pop())+"");
                      n--;
                  }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button b1;
    private java.awt.Choice choice1;
    private java.awt.Choice choice2;
    private java.awt.Label l1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
